project:
  type: website

website:
  title: "Group Project" 
  search: true

  navbar:
    background: "#2563eb"
    foreground: "white"
    collapse-below: lg

    left:
      - text: "Singapore Fertility Trends: Project Proposal"
        menu:
          - text: "1. Data Preparation & EDA"
            href: data-preparation-and-eda.qmd
          - text: "2. Cross Correlation Analysis"
            href: correlation-analysis.qmd
          - text: "3. Panel Regression Analysis"
            href: regression-analysis.qmd
          - text: "4. Storyboard of Shiny App"
            href: storyboard.qmd
          - text: "5. Work Allocation"
            href: allocation.qmd
      - text: "Meeting Minutes"
        href: meeting.qmd
      - text: "Shiny App"
        href: https://cheokenqi.shinyapps.io/ISSS608-GroupProject/
      - text: "Project Poster"
        href: project_poster.qmd
    right:
      - icon: house
        href: index.qmd
        aria-label: Home
      - icon: person-circle
        href: about.qmd

  page-footer:
    left: "Made with Quarto"
    right: "ISSS608"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    toc-title: "On this page"
    smooth-scroll: true

editor: visual