project:
  type: website
 
website:
  title: "Group Project"
  search: true

  navbar:
    background: "#2563eb"   
    foreground: "white"
    collapse-below: lg

    left:
      - text: "Singapore Fertility Trends: A Visual Analytics Study"
        menu:
          - text: "Data Preparation and EDA"
            href: data preparation and eda.qmd 
          - text: "Correlation Analysis"
            href: correlation analysis.qmd   
          - text: "Regression Analysis"
            href: regression analysis.qmd  
          - text: "Storyboard"
            href: storyboard.qmd      
    right:
      - icon: house
        href: index.qmd
        aria-label: Home
      - icon: person-circle
        href: about.qmd

  page-footer:
    left: "Made with Quarto"
    right: "ISSS608"
 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    toc-title: "On this page"
    smooth-scroll: true

editor: visual