{
  "hash": "90b0453493d68ceae0038270074aa5c8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Panel Regression Analysis: Singapore Fertility Trends: A Visual Analytics Study\"\nauthor: \"G1 T16 - Cheok En Qi and Teong Sze Ching\"\ndate: \"March 6, 2026\"\ndate-modified: \"last-modified\"\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n## Load dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, knitr, patchwork, plm, lmtest, sandwich)\n\ncoef_table <- function(model) {\n  ct <- coeftest(model, vcov = vcovHC(model, type = \"HC1\"))\n  data.frame(\n    term = rownames(ct),\n    estimate = unname(ct[, 1]),\n    std_error = unname(ct[, 2]),\n    statistic = unname(ct[, 3]),\n    p_value = unname(ct[, 4]),\n    row.names = NULL,\n    check.names = FALSE\n  )\n}\n\nanalysis_df <- readRDS(\"data/analysis_df.rds\")\ntfr_df <- readRDS(\"data/tfr_df.rds\")\nasfr_df <- readRDS(\"data/asfr_df.rds\")\nseries_key <- readRDS(\"data/series_key.rds\")\n```\n:::\n\n\n# Panel Regression Analysis\n\nBecause the data contain repeated observations across age groups and years, panel regression is more suitable than a simple regression model.\n\nThe cross-correlation analysis was first used to explore possible lead-lag patterns across a 5-year window. Since the strongest co-movement for both marriage and divorce was observed at lag 0, the panel regression section focuses on the same-year specification as the main formal model. This allows the analysis to estimate the direction, coefficient size, and statistical significance of the relationships more explicitly within a panel-data framework.\n\nUnlike the cross-correlation section, which uses the overall yearly series to examine the aggregate timing pattern, the panel regression here uses age-group-by-year observations with ASFR as the dependent variable. This makes age group an important part of the model structure, because fertility levels differ substantially across age groups and should not be treated as one pooled series.\n\n## 1.1 Organising the EDA output for Panel Regression\n\nThe dataset prepared in the EDA section is already structurally suitable for panel regression. The regression section does not create a completely new dataset. Specifically, it combines the age-specific fertility dataset (asfr_df) with the yearly marriage and divorce indicators from analysis_df to form the panel dataset used for modelling.\n\n::: panel-tabset\n## Visual\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Sample of the age-group-by-year panel dataset\n\n| year|age_group | asfr| marriage| divorce|\n|----:|:---------|----:|--------:|-------:|\n| 1980|15-19     | 12.7|      9.8|     0.8|\n| 1981|15-19     | 11.8|     10.6|     0.9|\n| 1982|15-19     | 11.4|      9.7|     0.9|\n| 1983|15-19     | 10.4|      9.0|     1.0|\n| 1984|15-19     | 10.3|      9.8|     0.9|\n| 1985|15-19     |  9.6|      9.2|     0.9|\n| 1986|15-19     |  8.6|      7.7|     1.0|\n| 1987|15-19     |  7.7|      8.9|     1.1|\n| 1988|15-19     |  7.3|      9.3|     1.1|\n| 1989|15-19     |  7.2|      8.7|     1.1|\n\n\n:::\n:::\n\n\n**Observation:**\\\nThe dataset is arranged in panel form, where each row represents one age group in one year. asfr is the age-specific fertility rate, measured as live births per 1,000 women in that age group. marriage is the crude marriage rate per 1,000 residents, and divorce is the crude divorce rate per 1,000 residents.\n\nBecause age group identifies who is being observed and year identifies when the observation takes place, this dataset is organised in a suitable format for panel regression. This is also where the regression section differs from the cross-correlation section: instead of using one overall fertility series, the regression uses repeated fertility observations across age groups over time.\n\n## Code\n\n``` r\npanel_df <- asfr_df %>%\n  transmute(\n    year,\n    age_group = as.character(age_band),\n    asfr = value\n  ) %>%\n  left_join(analysis_df %>% select(year, marriage, divorce), by = \"year\") %>%\n  drop_na(age_group, year, asfr, marriage, divorce) %>%\n  arrange(age_group, year)\n\npanel_preview <- panel_df %>%\n  slice_head(n = 10)\n\nknitr::kable(\n  panel_preview,\n  digits = 3,\n  caption = \"Preview of the age-group-by-year panel dataset\"\n)\n```\n:::\n\n------------------------------------------------------------------------\n\n## 1.2 Exploratory Panel Visualisation\n\nBefore performing regression, it is useful to visualise the panel data. This step helps answer a basic question before modelling: Do the age groups actually look different from one another? If they do, panel methods make more sense because the analysis needs to account for those differences.\n\n::: panel-tabset\n## Visual\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](regression-analysis_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n**Observation:**\\\nThe chart shows that fertility is not the same across age groups. Younger and older groups have much lower ASFR, while the middle age groups, especially 25-29 and 30-34, have much higher fertility levels. The chart also shows that the lines move differently over time. For example, some younger age groups generally decline, while older age groups such as 35-39 become more important later on. This tells us that fertility behaviour differs across age groups, so a model that recognises those group differences is more appropriate than treating all observations as one pooled series.\n\n## Code\n\n``` r\nggplot(panel_df, aes(x = year, y = asfr, colour = age_group)) +\n  geom_line(linewidth = 0.9) +\n  labs(\n    title = \"Age-Specific Fertility Rates by Age Group\",\n    x = \"Year\",\n    y = \"ASFR (births per 1,000 women)\",\n    colour = \"Age group\"\n  ) +\n  theme_minimal() +\n  theme(plot.title = element_text(face = \"bold\"))\n```\n:::\n\n------------------------------------------------------------------------\n\n## 1.3 Fixed-Effects Panel Regression Model\n\nThis model is performed because it helps answer the following question:\n\n“Within the same age group, when marriage or divorce changes over time, does fertility also tend to change?”\n\nSome age groups naturally have higher fertility than others. The fixed-effects model accounts for these stable age-group differences by focusing on how fertility changes within the same age group across years.\n\n::: panel-tabset\n## Visual\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Fixed-effects panel regression with robust standard errors\n\n|term     | estimate| std_error| statistic| p_value|\n|:--------|--------:|---------:|---------:|-------:|\n|marriage |    5.187|     2.641|     1.964|    0.05|\n|divorce  |    0.440|     5.015|     0.088|    0.93|\n\n\n:::\n:::\n\n\n**Observation:**\\\nThe fixed-effects model estimates a positive coefficient for marriage of 5.187. This suggests that, within the same age group over time, a 1-point increase in the crude marriage rate per 1,000 residents is associated with an increase of about 5.187 births per 1,000 women in ASFR, holding divorce constant. However, the p-value is 0.050, which places the result at the margin of the conventional 5% significance threshold. This should therefore be interpreted as borderline rather than strong statistical evidence.\n\nIn contrast, the divorce coefficient is 0.440, indicating only a very weak relationship with fertility in this model. The evidence for divorce is not statistically strong.\n\nOverall, the fixed-effects model suggests that marriage may have a modest positive association with fertility, while divorce does not show clear evidence of a meaningful association.\n\nNote: Although the fixed-effects model compares changes within each age group over time, it still estimates one overall coefficient for each explanatory variable. This means each age group contributes to the estimation, but the final regression table reports the combined relationship for the full panel.\n\n## Code\n\n``` r\npanel_pdata <- pdata.frame(panel_df, index = c(\"age_group\", \"year\"))\n\nfe_model <- plm(\n  asfr ~ marriage + divorce,\n  data = panel_pdata,\n  model = \"within\"\n)\n\nfe_tbl <- coef_table(fe_model)\n\nknitr::kable(\n  fe_tbl,\n  digits = 3,\n  caption = \"Fixed-effects panel regression with robust standard errors\"\n)\n```\n:::\n\n------------------------------------------------------------------------\n\n## 1.4 Random-Effects Panel Regression and Hausman Comparison\n\nThe random-effects model is included mainly as a supporting comparison to the fixed-effects model. Since the fixed-effects model focuses on changes within the same age group over time, the random-effects model uses both changes within age groups over time and differences across age groups. We care about differences between age groups because fertility is naturally higher in some age groups than others, as shown in Section 1.2.\n\nAfter performing the random-effects model, a Hausman test is used to compare the fixed-effects and random-effects results and check whether the overall conclusion changes meaningfully.\n\n::: panel-tabset\n## Visual\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Random-effects panel regression with robust standard errors\n\n|term        | estimate| std_error| statistic| p_value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |    1.342|     7.218|     0.186|   0.853|\n|marriage    |    5.187|     2.645|     1.961|   0.051|\n|divorce     |    0.440|     5.023|     0.088|   0.930|\n\n\n:::\n\n::: {.cell-output-display}\n\n\nTable: Hausman test: fixed effects versus random effects\n\n| statistic| p_value|\n|---------:|-------:|\n|         0|       1|\n\n\n:::\n:::\n\n\n**Observation:**\\\nThe random-effects results are very similar to the fixed-effects results. Marriage still has a positive coefficient of about 5.187, but its p-value of 0.051 is slightly above the conventional 5% threshold. This means the result is not statistically significant at the 5% level, although it may still be described as borderline or weak evidence of a positive association.\n\nDivorce continues to show no meaningful statistical relationship with fertility, with a p-value of 0.930.\n\nThe Hausman test gives a p-value of 1.000, suggesting no meaningful difference between the fixed-effects and random-effects results in this dataset.\n\nOverall, both models lead to the same broad conclusion: marriage shows a modest positive but statistically weak relationship with fertility, while divorce does not show clear evidence of association.\n\n## Code\n\n``` r\nre_model <- plm(\n  asfr ~ marriage + divorce,\n  data = panel_pdata,\n  model = \"random\"\n)\n\nre_tbl <- coef_table(re_model)\n\nhausman_test <- phtest(fe_model, re_model)\nhausman_tbl <- tibble(\n  statistic = unname(hausman_test$statistic),\n  p_value = unname(hausman_test$p.value)\n)\n\nknitr::kable(\n  re_tbl,\n  digits = 3,\n  caption = \"Random-effects panel regression with robust standard errors\"\n)\n\nknitr::kable(\n  hausman_tbl,\n  digits = 3,\n  caption = \"Hausman test: fixed effects versus random effects\"\n)\n```\n:::\n\n------------------------------------------------------------------------\n\n## 1.5 Coefficient Comparison Across Panel Models\n\nThis chart compares the estimated coefficients across the fixed-effects and random-effects models. It helps show whether the direction and size of the marriage and divorce coefficients remain similar across the two panel specifications.\n\n::: panel-tabset\n## Visual\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](regression-analysis_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n**Observation:**\\\nThe chart compares the estimated coefficients from the fixed-effects and random-effects models. Marriage remains positive in both models, while divorce remains much weaker. This suggests that the direction and relative size of the coefficients are broadly consistent across the two panel specifications.\n\n## Code\n\n``` r\ncoef_plot_df <- bind_rows(\n  coef_table(fe_model) %>%\n    mutate(model = \"Fixed Effects\"),\n  coef_table(re_model) %>%\n    mutate(model = \"Random Effects\")\n) %>%\n  mutate(\n    term = case_when(\n      term == \"marriage\" ~ \"Marriage\",\n      term == \"divorce\" ~ \"Divorce\",\n      TRUE ~ term\n    )\n  ) %>%\n  filter(term %in% c(\"Marriage\", \"Divorce\"))\n\nggplot(coef_plot_df, aes(x = model, y = estimate, fill = term)) +\n  geom_col(position = position_dodge(width = 0.7), width = 0.6) +\n  geom_text(\n    aes(label = round(estimate, 2)),\n    position = position_dodge(width = 0.7),\n    vjust = -0.4,\n    size = 3.5\n  ) +\n  labs(\n    title = \"Coefficient Comparison Across Panel Regression Models\",\n    x = \"Model\",\n    y = \"Coefficient Estimate\",\n    fill = \"Variable\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(face = \"bold\"),\n    legend.position = \"top\"\n  )\n```\n:::\n\n------------------------------------------------------------------------\n\n## Conclusion\n\nAcross both panel models, marriage has a positive coefficient and remains close to the threshold of statistical significance, while divorce does not show a clear relationship with fertility in this dataset. These results suggest that marriage may be more closely associated with fertility patterns than divorce, although the overall evidence remains modest rather than strong.\n",
    "supporting": [
      "regression-analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}