{
  "hash": "2bd93c6665ad6d62806ced0fa93954e3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Cross-Correlation Analysis: Singapore Fertility Trends: A Visual Analytics Study\"\nauthor: \"G1 T16 - Cheok En Qi and Teong Sze Ching\"\ndate: \"March 6, 2026\"\ndate-modified: \"last-modified\"\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n## Load dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, knitr, patchwork, TSstudio)\n\nanalysis_df <- readRDS(\"data/analysis_df.rds\")\ntfr_df <- readRDS(\"data/tfr_df.rds\")\nasfr_df <- readRDS(\"data/asfr_df.rds\")\nseries_key <- readRDS(\"data/series_key.rds\")\n\nextract_ccf_tbl <- function(x, y, x_name, y_name, lag_max = 5) {\n  ccf_obj <- ccf(x, y, lag.max = lag_max, plot = FALSE, na.action = na.omit)\n  tibble(\n    lag = as.numeric(ccf_obj$lag),\n    correlation = as.numeric(ccf_obj$acf),\n    pair = paste(x_name, \"vs\", y_name)\n  )\n}\n\nget_peak_ccf <- function(df, pair_name) {\n  df %>%\n    slice_max(order_by = abs(correlation), n = 1, with_ties = FALSE) %>%\n    transmute(\n      Pair = pair_name,\n      `Peak Lag (Years)` = lag,\n      `Peak Correlation` = correlation\n    )\n}\n```\n:::\n\n\n# Cross-Correlation Analysis\n\nOur group uses cross-correlation analysis to explore how fertility, marriage, and divorce move relative to one another across different lags. Unlike ordinary correlation, Cross-correlation captures the direction, strength and timing of co-movement between fertility and the demographic indicators, showing whether the series move together or in opposite directions, how strong that pattern is, and the lag at which it is strongest. This is useful for exploring demographic timing, such as whether changes in marriage or divorce tend to occur earlier or later than changes in total fertility rate (TFR).\n\nThe results should be interpreted as exploratory evidence of co-movement across time rather than proof of cause and effect. They are also intended to complement the regression section by helping to identify which lag values may be worth testing for later modelling.\n\n## 1.1 Organising the EDA Output for Cross-Correlation\n\nThe dataset prepared in the EDA section is already suitable for cross-correlation analysis. The main requirement is to keep the yearly observations in chronological order and retain the variables needed for the lead-lag comparison: TFR, marriage, and divorce.\n\n::: panel-tabset\n## Visual\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Sample of the yearly dataset used for cross-correlation analysis\n\n| year|  tfr| marriage| divorce|\n|----:|----:|--------:|-------:|\n| 1980| 1.82|      9.8|     0.8|\n| 1981| 1.78|     10.6|     0.9|\n| 1982| 1.74|      9.7|     0.9|\n| 1983| 1.61|      9.0|     1.0|\n| 1984| 1.62|      9.8|     0.9|\n| 1985| 1.61|      9.2|     0.9|\n| 1986| 1.43|      7.7|     1.0|\n| 1987| 1.62|      8.9|     1.1|\n| 1988| 1.96|      9.3|     1.1|\n| 1989| 1.75|      8.7|     1.1|\n\n\n:::\n:::\n\n\n## Code\n\n``` r\nccf_df <- analysis_df %>%\n  select(year, tfr, marriage, divorce) %>%\n  drop_na() %>%\n  arrange(year)\n\nccf_preview <- ccf_df %>%\n  slice_head(n = 10)\n\nknitr::kable(\n  ccf_preview,\n  digits = 3,\n  caption = \"Sample of the yearly dataset used for cross-correlation analysis\"\n)\n```\n:::\n\n------------------------------------------------------------------------\n\n## 1.2 Cross-Correlation Between TFR and Marriage\n\nThis section explores whether the co-movement between TFR and marriage is strongest in the same year or at earlier or later years. This helps answer the following question:\n\n“Does marriage move most closely with fertility in the same year or does the strongest pattern appear with a time shift?”\n\nA 5-year lag window was chosen since changes in marriage and fertility are more likely to be related within a reasonably near time horizon rather than over very long lags.\n\n::: panel-tabset\n## Visual\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-877b6d0296837ac4a3bf\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-877b6d0296837ac4a3bf\">{\"x\":{\"data\":[{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001,1.1000000000000001,1.1200000000000001,1.04,0.96999999999999997,0.96999999999999997],\"y\":[9.8000000000000025,10.6,9.7000000000000011,9,9.8000000000000025,9.2000000000000011,7.7000000000000002,8.9000000000000004,9.3000000000000025,8.7000000000000011,8.5999999999999996,8.7000000000000011,8.9000000000000004,8.5999999999999996,8.2000000000000011,8.0999999999999996,7.7000000000000002,8.0999999999999996,7.0999999999999996,7.7999999999999998,6.7000000000000002,6.5,6.5999999999999996,6.2999999999999998,6.2999999999999998,6.4000000000000004,6.5,6.4000000000000004,6.5,6.5999999999999996,6.0999999999999996,6.7000000000000002,6.7000000000000002,6.2999999999999998,6.7999999999999998,6.7000000000000002,6.5999999999999996,6.5999999999999996,6.4000000000000004,5.9000000000000004,5.2000000000000002,6.5,6.7000000000000002,6.4000000000000004,5.9000000000000004],\"mode\":\"markers\",\"type\":\"scatter\",\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null},{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001,1.1000000000000001,1.1200000000000001,1.04,0.96999999999999997],\"y\":[10.6,9.7000000000000011,9,9.8000000000000025,9.2000000000000011,7.7000000000000002,8.9000000000000004,9.3000000000000025,8.7000000000000011,8.5999999999999996,8.7000000000000011,8.9000000000000004,8.5999999999999996,8.2000000000000011,8.0999999999999996,7.7000000000000002,8.0999999999999996,7.0999999999999996,7.7999999999999998,6.7000000000000002,6.5,6.5999999999999996,6.2999999999999998,6.2999999999999998,6.4000000000000004,6.5,6.4000000000000004,6.5,6.5999999999999996,6.0999999999999996,6.7000000000000002,6.7000000000000002,6.2999999999999998,6.7999999999999998,6.7000000000000002,6.5999999999999996,6.5999999999999996,6.4000000000000004,5.9000000000000004,5.2000000000000002,6.5,6.7000000000000002,6.4000000000000004,5.9000000000000004],\"mode\":\"markers\",\"type\":\"scatter\",\"marker\":{\"color\":\"rgba(255,127,14,1)\",\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"xaxis\":\"x2\",\"yaxis\":\"y\",\"frame\":null},{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001,1.1000000000000001,1.1200000000000001,1.04],\"y\":[9.7000000000000011,9,9.8000000000000025,9.2000000000000011,7.7000000000000002,8.9000000000000004,9.3000000000000025,8.7000000000000011,8.5999999999999996,8.7000000000000011,8.9000000000000004,8.5999999999999996,8.2000000000000011,8.0999999999999996,7.7000000000000002,8.0999999999999996,7.0999999999999996,7.7999999999999998,6.7000000000000002,6.5,6.5999999999999996,6.2999999999999998,6.2999999999999998,6.4000000000000004,6.5,6.4000000000000004,6.5,6.5999999999999996,6.0999999999999996,6.7000000000000002,6.7000000000000002,6.2999999999999998,6.7999999999999998,6.7000000000000002,6.5999999999999996,6.5999999999999996,6.4000000000000004,5.9000000000000004,5.2000000000000002,6.5,6.7000000000000002,6.4000000000000004,5.9000000000000004],\"mode\":\"markers\",\"type\":\"scatter\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x3\",\"yaxis\":\"y\",\"frame\":null},{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001,1.1000000000000001,1.1200000000000001],\"y\":[9,9.8000000000000025,9.2000000000000011,7.7000000000000002,8.9000000000000004,9.3000000000000025,8.7000000000000011,8.5999999999999996,8.7000000000000011,8.9000000000000004,8.5999999999999996,8.2000000000000011,8.0999999999999996,7.7000000000000002,8.0999999999999996,7.0999999999999996,7.7999999999999998,6.7000000000000002,6.5,6.5999999999999996,6.2999999999999998,6.2999999999999998,6.4000000000000004,6.5,6.4000000000000004,6.5,6.5999999999999996,6.0999999999999996,6.7000000000000002,6.7000000000000002,6.2999999999999998,6.7999999999999998,6.7000000000000002,6.5999999999999996,6.5999999999999996,6.4000000000000004,5.9000000000000004,5.2000000000000002,6.5,6.7000000000000002,6.4000000000000004,5.9000000000000004],\"mode\":\"markers\",\"type\":\"scatter\",\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y2\",\"frame\":null},{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001,1.1000000000000001],\"y\":[9.8000000000000025,9.2000000000000011,7.7000000000000002,8.9000000000000004,9.3000000000000025,8.7000000000000011,8.5999999999999996,8.7000000000000011,8.9000000000000004,8.5999999999999996,8.2000000000000011,8.0999999999999996,7.7000000000000002,8.0999999999999996,7.0999999999999996,7.7999999999999998,6.7000000000000002,6.5,6.5999999999999996,6.2999999999999998,6.2999999999999998,6.4000000000000004,6.5,6.4000000000000004,6.5,6.5999999999999996,6.0999999999999996,6.7000000000000002,6.7000000000000002,6.2999999999999998,6.7999999999999998,6.7000000000000002,6.5999999999999996,6.5999999999999996,6.4000000000000004,5.9000000000000004,5.2000000000000002,6.5,6.7000000000000002,6.4000000000000004,5.9000000000000004],\"mode\":\"markers\",\"type\":\"scatter\",\"marker\":{\"color\":\"rgba(148,103,189,1)\",\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"xaxis\":\"x2\",\"yaxis\":\"y2\",\"frame\":null},{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001],\"y\":[9.2000000000000011,7.7000000000000002,8.9000000000000004,9.3000000000000025,8.7000000000000011,8.5999999999999996,8.7000000000000011,8.9000000000000004,8.5999999999999996,8.2000000000000011,8.0999999999999996,7.7000000000000002,8.0999999999999996,7.0999999999999996,7.7999999999999998,6.7000000000000002,6.5,6.5999999999999996,6.2999999999999998,6.2999999999999998,6.4000000000000004,6.5,6.4000000000000004,6.5,6.5999999999999996,6.0999999999999996,6.7000000000000002,6.7000000000000002,6.2999999999999998,6.7999999999999998,6.7000000000000002,6.5999999999999996,6.5999999999999996,6.4000000000000004,5.9000000000000004,5.2000000000000002,6.5,6.7000000000000002,6.4000000000000004,5.9000000000000004],\"mode\":\"markers\",\"type\":\"scatter\",\"marker\":{\"color\":\"rgba(140,86,75,1)\",\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"xaxis\":\"x3\",\"yaxis\":\"y2\",\"frame\":null}],\"layout\":{\"xaxis\":{\"domain\":[0,0.3133333333333333],\"automargin\":true,\"title\":\"\",\"range\":[0.96757500000000007,2.0579999999999998],\"anchor\":\"y2\"},\"xaxis2\":{\"domain\":[0.35333333333333333,0.64666666666666661],\"automargin\":true,\"title\":\"\",\"range\":[0.96757500000000007,2.0579999999999998],\"anchor\":\"y2\"},\"xaxis3\":{\"domain\":[0.68666666666666665,1],\"automargin\":true,\"title\":\"\",\"range\":[0.96757500000000007,2.0579999999999998],\"anchor\":\"y2\"},\"yaxis2\":{\"domain\":[0,0.47999999999999998],\"automargin\":true,\"range\":[5.1869999999999994,11.130000000000001],\"title\":[],\"anchor\":\"x\"},\"yaxis\":{\"domain\":[0.52000000000000002,1],\"automargin\":true,\"range\":[5.1869999999999994,11.130000000000001],\"title\":[],\"anchor\":\"x\"},\"annotations\":[{\"text\":\"Lag 0 (0.878)\",\"xref\":\"paper\",\"yref\":\"paper\",\"yanchor\":\"bottom\",\"xanchor\":\"center\",\"align\":\"center\",\"x\":0.15666666666666665,\"y\":0.95199999999999996,\"showarrow\":false},{\"text\":\"Lag 1 (0.769)\",\"xref\":\"paper\",\"yref\":\"paper\",\"yanchor\":\"bottom\",\"xanchor\":\"center\",\"align\":\"center\",\"x\":0.5,\"y\":0.95199999999999996,\"showarrow\":false},{\"text\":\"Lag 2 (0.671)\",\"xref\":\"paper\",\"yref\":\"paper\",\"yanchor\":\"bottom\",\"xanchor\":\"center\",\"align\":\"center\",\"x\":0.84333333333333327,\"y\":0.95199999999999996,\"showarrow\":false},{\"text\":\"Lag 3 (0.596)\",\"xref\":\"paper\",\"yref\":\"paper\",\"yanchor\":\"bottom\",\"xanchor\":\"center\",\"align\":\"center\",\"x\":0.15666666666666665,\"y\":0.432,\"showarrow\":false},{\"text\":\"Lag 4 (0.522)\",\"xref\":\"paper\",\"yref\":\"paper\",\"yanchor\":\"bottom\",\"xanchor\":\"center\",\"align\":\"center\",\"x\":0.5,\"y\":0.432,\"showarrow\":false},{\"text\":\"Lag 5 (0.421)\",\"xref\":\"paper\",\"yref\":\"paper\",\"yanchor\":\"bottom\",\"xanchor\":\"center\",\"align\":\"center\",\"x\":0.84333333333333327,\"y\":0.432,\"showarrow\":false}],\"shapes\":[],\"images\":[],\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"hovermode\":\"closest\",\"showlegend\":false,\"title\":\"Cross-Correlation: TFR and Marriage\"},\"attrs\":{\"27001a2070b6\":{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001,1.1000000000000001,1.1200000000000001,1.04,0.96999999999999997,0.96999999999999997],\"y\":[9.8000000000000025,10.6,9.7000000000000011,9,9.8000000000000025,9.2000000000000011,7.7000000000000002,8.9000000000000004,9.3000000000000025,8.7000000000000011,8.5999999999999996,8.7000000000000011,8.9000000000000004,8.5999999999999996,8.2000000000000011,8.0999999999999996,7.7000000000000002,8.0999999999999996,7.0999999999999996,7.7999999999999998,6.7000000000000002,6.5,6.5999999999999996,6.2999999999999998,6.2999999999999998,6.4000000000000004,6.5,6.4000000000000004,6.5,6.5999999999999996,6.0999999999999996,6.7000000000000002,6.7000000000000002,6.2999999999999998,6.7999999999999998,6.7000000000000002,6.5999999999999996,6.5999999999999996,6.4000000000000004,5.9000000000000004,5.2000000000000002,6.5,6.7000000000000002,6.4000000000000004,5.9000000000000004],\"mode\":\"markers\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter\"},\"27007edf4bd7\":{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001,1.1000000000000001,1.1200000000000001,1.04,0.96999999999999997],\"y\":[10.6,9.7000000000000011,9,9.8000000000000025,9.2000000000000011,7.7000000000000002,8.9000000000000004,9.3000000000000025,8.7000000000000011,8.5999999999999996,8.7000000000000011,8.9000000000000004,8.5999999999999996,8.2000000000000011,8.0999999999999996,7.7000000000000002,8.0999999999999996,7.0999999999999996,7.7999999999999998,6.7000000000000002,6.5,6.5999999999999996,6.2999999999999998,6.2999999999999998,6.4000000000000004,6.5,6.4000000000000004,6.5,6.5999999999999996,6.0999999999999996,6.7000000000000002,6.7000000000000002,6.2999999999999998,6.7999999999999998,6.7000000000000002,6.5999999999999996,6.5999999999999996,6.4000000000000004,5.9000000000000004,5.2000000000000002,6.5,6.7000000000000002,6.4000000000000004,5.9000000000000004],\"mode\":\"markers\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter\"},\"2700370515e8\":{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001,1.1000000000000001,1.1200000000000001,1.04],\"y\":[9.7000000000000011,9,9.8000000000000025,9.2000000000000011,7.7000000000000002,8.9000000000000004,9.3000000000000025,8.7000000000000011,8.5999999999999996,8.7000000000000011,8.9000000000000004,8.5999999999999996,8.2000000000000011,8.0999999999999996,7.7000000000000002,8.0999999999999996,7.0999999999999996,7.7999999999999998,6.7000000000000002,6.5,6.5999999999999996,6.2999999999999998,6.2999999999999998,6.4000000000000004,6.5,6.4000000000000004,6.5,6.5999999999999996,6.0999999999999996,6.7000000000000002,6.7000000000000002,6.2999999999999998,6.7999999999999998,6.7000000000000002,6.5999999999999996,6.5999999999999996,6.4000000000000004,5.9000000000000004,5.2000000000000002,6.5,6.7000000000000002,6.4000000000000004,5.9000000000000004],\"mode\":\"markers\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter\"},\"270013e5162f\":{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001,1.1000000000000001,1.1200000000000001],\"y\":[9,9.8000000000000025,9.2000000000000011,7.7000000000000002,8.9000000000000004,9.3000000000000025,8.7000000000000011,8.5999999999999996,8.7000000000000011,8.9000000000000004,8.5999999999999996,8.2000000000000011,8.0999999999999996,7.7000000000000002,8.0999999999999996,7.0999999999999996,7.7999999999999998,6.7000000000000002,6.5,6.5999999999999996,6.2999999999999998,6.2999999999999998,6.4000000000000004,6.5,6.4000000000000004,6.5,6.5999999999999996,6.0999999999999996,6.7000000000000002,6.7000000000000002,6.2999999999999998,6.7999999999999998,6.7000000000000002,6.5999999999999996,6.5999999999999996,6.4000000000000004,5.9000000000000004,5.2000000000000002,6.5,6.7000000000000002,6.4000000000000004,5.9000000000000004],\"mode\":\"markers\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter\"},\"270075ff5031\":{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001,1.1000000000000001],\"y\":[9.8000000000000025,9.2000000000000011,7.7000000000000002,8.9000000000000004,9.3000000000000025,8.7000000000000011,8.5999999999999996,8.7000000000000011,8.9000000000000004,8.5999999999999996,8.2000000000000011,8.0999999999999996,7.7000000000000002,8.0999999999999996,7.0999999999999996,7.7999999999999998,6.7000000000000002,6.5,6.5999999999999996,6.2999999999999998,6.2999999999999998,6.4000000000000004,6.5,6.4000000000000004,6.5,6.5999999999999996,6.0999999999999996,6.7000000000000002,6.7000000000000002,6.2999999999999998,6.7999999999999998,6.7000000000000002,6.5999999999999996,6.5999999999999996,6.4000000000000004,5.9000000000000004,5.2000000000000002,6.5,6.7000000000000002,6.4000000000000004,5.9000000000000004],\"mode\":\"markers\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter\"},\"2700ba8164d\":{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001],\"y\":[9.2000000000000011,7.7000000000000002,8.9000000000000004,9.3000000000000025,8.7000000000000011,8.5999999999999996,8.7000000000000011,8.9000000000000004,8.5999999999999996,8.2000000000000011,8.0999999999999996,7.7000000000000002,8.0999999999999996,7.0999999999999996,7.7999999999999998,6.7000000000000002,6.5,6.5999999999999996,6.2999999999999998,6.2999999999999998,6.4000000000000004,6.5,6.4000000000000004,6.5,6.5999999999999996,6.0999999999999996,6.7000000000000002,6.7000000000000002,6.2999999999999998,6.7999999999999998,6.7000000000000002,6.5999999999999996,6.5999999999999996,6.4000000000000004,5.9000000000000004,5.2000000000000002,6.5,6.7000000000000002,6.4000000000000004,5.9000000000000004],\"mode\":\"markers\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter\"}},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"subplot\":true,\".hideLegend\":true,\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n\n::: {.cell-output-display}\n\n\nTable: Cross-correlation values between TFR and marriage across lags\n\n| lag| correlation|pair            |\n|---:|-----------:|:---------------|\n|  -5|       0.421|TFR vs Marriage |\n|  -4|       0.522|TFR vs Marriage |\n|  -3|       0.596|TFR vs Marriage |\n|  -2|       0.671|TFR vs Marriage |\n|  -1|       0.769|TFR vs Marriage |\n|   0|       0.878|TFR vs Marriage |\n|   1|       0.812|TFR vs Marriage |\n|   2|       0.742|TFR vs Marriage |\n|   3|       0.772|TFR vs Marriage |\n|   4|       0.751|TFR vs Marriage |\n|   5|       0.686|TFR vs Marriage |\n\n\n:::\n:::\n\n\n**Observation:**\\\nThe cross-correlation between TFR and marriage is positive across all tested lags, indicating that the two series generally move in the same direction. The strongest value appears at lag 0 (0.878), suggesting that the clearest co-movement occurs in the same year rather than after a time shift. The correlations remain relatively high at nearby lags, such as lag -1 (0.769), lag 1 (0.812), and lag 2 (0.742), but they gradually weaken as the lag moves further away from zero. This suggests that the alignment between marriage and fertility is strongest in the near term with same-year timing appearing most prominent. Based on this pattern, lag 0 and nearby short lags may be the most relevant candidates for further testing in the regression analysis.\n\n## Code\n\n``` r\nlag_max <- 5\n\ntfr_ts <- ts(ccf_df$tfr, start = min(ccf_df$year), frequency = 1)\nmarriage_ts <- ts(ccf_df$marriage, start = min(ccf_df$year), frequency = 1)\ndivorce_ts <- ts(ccf_df$divorce, start = min(ccf_df$year), frequency = 1)\n\nTSstudio::ccf_plot(\n  x = tfr_ts,\n  y = marriage_ts,\n  lags = 0:lag_max,\n  title = \"Cross-Correlation: TFR and Marriage\"\n)\n\nccf_marriage_tbl <- extract_ccf_tbl(\n  x = ccf_df$tfr,\n  y = ccf_df$marriage,\n  x_name = \"TFR\",\n  y_name = \"Marriage\",\n  lag_max = lag_max\n)\n\nknitr::kable(\n  ccf_marriage_tbl,\n  digits = 3,\n  caption = \"Cross-correlation values between TFR and marriage across lags\"\n)\n```\n:::\n\n------------------------------------------------------------------------\n\n## 1.3 Cross-Correlation Between TFR and Divorce\n\nThis section applies the same lag-based comparison to divorce. It helps answer a similar question:\n\n“Does divorce move most closely with fertility in the same year, or does the clearest timing pattern appear earlier or later?”\n\n::: panel-tabset\n## Visual\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-7e298e42e5bb0d8d173f\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-7e298e42e5bb0d8d173f\">{\"x\":{\"data\":[{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001,1.1000000000000001,1.1200000000000001,1.04,0.96999999999999997,0.96999999999999997],\"y\":[0.80000000000000004,0.90000000000000002,0.90000000000000002,1,0.90000000000000002,0.90000000000000002,1,1.1000000000000001,1.1000000000000001,1.1000000000000001,1.3,1.6000000000000001,1.3999999999999999,1.3999999999999999,1.3,1.3999999999999999,1.5,1.6000000000000001,1.8,1.6000000000000001,1.6000000000000001,1.5,1.7,1.8999999999999999,1.8,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8,1.8999999999999999,1.7,1.8999999999999999,1.7,1.7,1.7],\"mode\":\"markers\",\"type\":\"scatter\",\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null},{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001,1.1000000000000001,1.1200000000000001,1.04,0.96999999999999997],\"y\":[0.90000000000000002,0.90000000000000002,1,0.90000000000000002,0.90000000000000002,1,1.1000000000000001,1.1000000000000001,1.1000000000000001,1.3,1.6000000000000001,1.3999999999999999,1.3999999999999999,1.3,1.3999999999999999,1.5,1.6000000000000001,1.8,1.6000000000000001,1.6000000000000001,1.5,1.7,1.8999999999999999,1.8,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8,1.8999999999999999,1.7,1.8999999999999999,1.7,1.7,1.7],\"mode\":\"markers\",\"type\":\"scatter\",\"marker\":{\"color\":\"rgba(255,127,14,1)\",\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"xaxis\":\"x2\",\"yaxis\":\"y\",\"frame\":null},{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001,1.1000000000000001,1.1200000000000001,1.04],\"y\":[0.90000000000000002,1,0.90000000000000002,0.90000000000000002,1,1.1000000000000001,1.1000000000000001,1.1000000000000001,1.3,1.6000000000000001,1.3999999999999999,1.3999999999999999,1.3,1.3999999999999999,1.5,1.6000000000000001,1.8,1.6000000000000001,1.6000000000000001,1.5,1.7,1.8999999999999999,1.8,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8,1.8999999999999999,1.7,1.8999999999999999,1.7,1.7,1.7],\"mode\":\"markers\",\"type\":\"scatter\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x3\",\"yaxis\":\"y\",\"frame\":null},{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001,1.1000000000000001,1.1200000000000001],\"y\":[1,0.90000000000000002,0.90000000000000002,1,1.1000000000000001,1.1000000000000001,1.1000000000000001,1.3,1.6000000000000001,1.3999999999999999,1.3999999999999999,1.3,1.3999999999999999,1.5,1.6000000000000001,1.8,1.6000000000000001,1.6000000000000001,1.5,1.7,1.8999999999999999,1.8,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8,1.8999999999999999,1.7,1.8999999999999999,1.7,1.7,1.7],\"mode\":\"markers\",\"type\":\"scatter\",\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y2\",\"frame\":null},{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001,1.1000000000000001],\"y\":[0.90000000000000002,0.90000000000000002,1,1.1000000000000001,1.1000000000000001,1.1000000000000001,1.3,1.6000000000000001,1.3999999999999999,1.3999999999999999,1.3,1.3999999999999999,1.5,1.6000000000000001,1.8,1.6000000000000001,1.6000000000000001,1.5,1.7,1.8999999999999999,1.8,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8,1.8999999999999999,1.7,1.8999999999999999,1.7,1.7,1.7],\"mode\":\"markers\",\"type\":\"scatter\",\"marker\":{\"color\":\"rgba(148,103,189,1)\",\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"xaxis\":\"x2\",\"yaxis\":\"y2\",\"frame\":null},{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001],\"y\":[0.90000000000000002,1,1.1000000000000001,1.1000000000000001,1.1000000000000001,1.3,1.6000000000000001,1.3999999999999999,1.3999999999999999,1.3,1.3999999999999999,1.5,1.6000000000000001,1.8,1.6000000000000001,1.6000000000000001,1.5,1.7,1.8999999999999999,1.8,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8,1.8999999999999999,1.7,1.8999999999999999,1.7,1.7,1.7],\"mode\":\"markers\",\"type\":\"scatter\",\"marker\":{\"color\":\"rgba(140,86,75,1)\",\"line\":{\"color\":\"rgba(140,86,75,1)\"}},\"error_y\":{\"color\":\"rgba(140,86,75,1)\"},\"error_x\":{\"color\":\"rgba(140,86,75,1)\"},\"line\":{\"color\":\"rgba(140,86,75,1)\"},\"xaxis\":\"x3\",\"yaxis\":\"y2\",\"frame\":null}],\"layout\":{\"xaxis\":{\"domain\":[0,0.3133333333333333],\"automargin\":true,\"title\":\"\",\"range\":[0.96757500000000007,2.0579999999999998],\"anchor\":\"y2\"},\"xaxis2\":{\"domain\":[0.35333333333333333,0.64666666666666661],\"automargin\":true,\"title\":\"\",\"range\":[0.96757500000000007,2.0579999999999998],\"anchor\":\"y2\"},\"xaxis3\":{\"domain\":[0.68666666666666665,1],\"automargin\":true,\"title\":\"\",\"range\":[0.96757500000000007,2.0579999999999998],\"anchor\":\"y2\"},\"yaxis2\":{\"domain\":[0,0.47999999999999998],\"automargin\":true,\"range\":[0.79800000000000004,2.1000000000000001],\"title\":[],\"anchor\":\"x\"},\"yaxis\":{\"domain\":[0.52000000000000002,1],\"automargin\":true,\"range\":[0.79800000000000004,2.1000000000000001],\"title\":[],\"anchor\":\"x\"},\"annotations\":[{\"text\":\"Lag 0 (-0.771)\",\"xref\":\"paper\",\"yref\":\"paper\",\"yanchor\":\"bottom\",\"xanchor\":\"center\",\"align\":\"center\",\"x\":0.15666666666666665,\"y\":0.95199999999999996,\"showarrow\":false},{\"text\":\"Lag 1 (-0.692)\",\"xref\":\"paper\",\"yref\":\"paper\",\"yanchor\":\"bottom\",\"xanchor\":\"center\",\"align\":\"center\",\"x\":0.5,\"y\":0.95199999999999996,\"showarrow\":false},{\"text\":\"Lag 2 (-0.605)\",\"xref\":\"paper\",\"yref\":\"paper\",\"yanchor\":\"bottom\",\"xanchor\":\"center\",\"align\":\"center\",\"x\":0.84333333333333327,\"y\":0.95199999999999996,\"showarrow\":false},{\"text\":\"Lag 3 (-0.517)\",\"xref\":\"paper\",\"yref\":\"paper\",\"yanchor\":\"bottom\",\"xanchor\":\"center\",\"align\":\"center\",\"x\":0.15666666666666665,\"y\":0.432,\"showarrow\":false},{\"text\":\"Lag 4 (-0.495)\",\"xref\":\"paper\",\"yref\":\"paper\",\"yanchor\":\"bottom\",\"xanchor\":\"center\",\"align\":\"center\",\"x\":0.5,\"y\":0.432,\"showarrow\":false},{\"text\":\"Lag 5 (-0.43)\",\"xref\":\"paper\",\"yref\":\"paper\",\"yanchor\":\"bottom\",\"xanchor\":\"center\",\"align\":\"center\",\"x\":0.84333333333333327,\"y\":0.432,\"showarrow\":false}],\"shapes\":[],\"images\":[],\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"hovermode\":\"closest\",\"showlegend\":false,\"title\":\"Cross-Correlation: TFR and Divorce\"},\"attrs\":{\"270013b6eb8\":{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001,1.1000000000000001,1.1200000000000001,1.04,0.96999999999999997,0.96999999999999997],\"y\":[0.80000000000000004,0.90000000000000002,0.90000000000000002,1,0.90000000000000002,0.90000000000000002,1,1.1000000000000001,1.1000000000000001,1.1000000000000001,1.3,1.6000000000000001,1.3999999999999999,1.3999999999999999,1.3,1.3999999999999999,1.5,1.6000000000000001,1.8,1.6000000000000001,1.6000000000000001,1.5,1.7,1.8999999999999999,1.8,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8,1.8999999999999999,1.7,1.8999999999999999,1.7,1.7,1.7],\"mode\":\"markers\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter\"},\"27005d917a95\":{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001,1.1000000000000001,1.1200000000000001,1.04,0.96999999999999997],\"y\":[0.90000000000000002,0.90000000000000002,1,0.90000000000000002,0.90000000000000002,1,1.1000000000000001,1.1000000000000001,1.1000000000000001,1.3,1.6000000000000001,1.3999999999999999,1.3999999999999999,1.3,1.3999999999999999,1.5,1.6000000000000001,1.8,1.6000000000000001,1.6000000000000001,1.5,1.7,1.8999999999999999,1.8,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8,1.8999999999999999,1.7,1.8999999999999999,1.7,1.7,1.7],\"mode\":\"markers\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter\"},\"27006b4f5481\":{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001,1.1000000000000001,1.1200000000000001,1.04],\"y\":[0.90000000000000002,1,0.90000000000000002,0.90000000000000002,1,1.1000000000000001,1.1000000000000001,1.1000000000000001,1.3,1.6000000000000001,1.3999999999999999,1.3999999999999999,1.3,1.3999999999999999,1.5,1.6000000000000001,1.8,1.6000000000000001,1.6000000000000001,1.5,1.7,1.8999999999999999,1.8,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8,1.8999999999999999,1.7,1.8999999999999999,1.7,1.7,1.7],\"mode\":\"markers\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter\"},\"27006eb846dd\":{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001,1.1000000000000001,1.1200000000000001],\"y\":[1,0.90000000000000002,0.90000000000000002,1,1.1000000000000001,1.1000000000000001,1.1000000000000001,1.3,1.6000000000000001,1.3999999999999999,1.3999999999999999,1.3,1.3999999999999999,1.5,1.6000000000000001,1.8,1.6000000000000001,1.6000000000000001,1.5,1.7,1.8999999999999999,1.8,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8,1.8999999999999999,1.7,1.8999999999999999,1.7,1.7,1.7],\"mode\":\"markers\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter\"},\"2700117f221d\":{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001,1.1000000000000001],\"y\":[0.90000000000000002,0.90000000000000002,1,1.1000000000000001,1.1000000000000001,1.1000000000000001,1.3,1.6000000000000001,1.3999999999999999,1.3999999999999999,1.3,1.3999999999999999,1.5,1.6000000000000001,1.8,1.6000000000000001,1.6000000000000001,1.5,1.7,1.8999999999999999,1.8,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8,1.8999999999999999,1.7,1.8999999999999999,1.7,1.7,1.7],\"mode\":\"markers\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter\"},\"270021a7460d\":{\"x\":[1.8200000000000001,1.78,1.74,1.6100000000000001,1.6200000000000001,1.6100000000000001,1.4299999999999999,1.6200000000000001,1.96,1.75,1.8300000000000001,1.73,1.72,1.74,1.71,1.6700000000000002,1.6600000000000001,1.6100000000000001,1.48,1.47,1.6000000000000001,1.4099999999999999,1.3700000000000001,1.27,1.26,1.26,1.28,1.29,1.28,1.22,1.1500000000000001,1.2,1.29,1.1900000000000002,1.25,1.24,1.2,1.1600000000000001,1.1400000000000001,1.1400000000000001],\"y\":[0.90000000000000002,1,1.1000000000000001,1.1000000000000001,1.1000000000000001,1.3,1.6000000000000001,1.3999999999999999,1.3999999999999999,1.3,1.3999999999999999,1.5,1.6000000000000001,1.8,1.6000000000000001,1.6000000000000001,1.5,1.7,1.8999999999999999,1.8,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,2,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8999999999999999,1.8,1.8999999999999999,1.7,1.8999999999999999,1.7,1.7,1.7],\"mode\":\"markers\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter\"}},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"subplot\":true,\".hideLegend\":true,\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n\n::: {.cell-output-display}\n\n\nTable: Cross-correlation values between TFR and divorce across lags\n\n| lag| correlation|pair           |\n|---:|-----------:|:--------------|\n|  -5|      -0.430|TFR vs Divorce |\n|  -4|      -0.495|TFR vs Divorce |\n|  -3|      -0.517|TFR vs Divorce |\n|  -2|      -0.605|TFR vs Divorce |\n|  -1|      -0.692|TFR vs Divorce |\n|   0|      -0.771|TFR vs Divorce |\n|   1|      -0.757|TFR vs Divorce |\n|   2|      -0.745|TFR vs Divorce |\n|   3|      -0.757|TFR vs Divorce |\n|   4|      -0.755|TFR vs Divorce |\n|   5|      -0.769|TFR vs Divorce |\n\n\n:::\n:::\n\n\n**Observation:**\\\nThe cross-correlation between TFR and divorce is negative across all tested lags, showing that the two series tend to move in opposite directions throughout the lag window. The largest absolute value occurs at lag 0 (-0.771), which suggests that the strongest co-movement appears in the same year rather than at a shifted lag. The correlation remains relatively strong for nearby positive lags, including lag 1 (-0.757) and lag 5 (-0.769), but is weaker for more distant negative lags. Compared with the marriage results, the divorce pattern is weaker in directionally positive co-movement and instead shows a stable inverse pattern with fertility. This indicates that divorce does not follow the same timing structure as marriage in relation to TFR.\n\n## Code\n\n``` r\nTSstudio::ccf_plot(\n  x = tfr_ts,\n  y = divorce_ts,\n  lags = 0:lag_max,\n  title = \"Cross-Correlation: TFR and Divorce\"\n)\n\nccf_divorce_tbl <- extract_ccf_tbl(\n  x = ccf_df$tfr,\n  y = ccf_df$divorce,\n  x_name = \"TFR\",\n  y_name = \"Divorce\",\n  lag_max = lag_max\n)\n\nknitr::kable(\n  ccf_divorce_tbl,\n  digits = 3,\n  caption = \"Cross-correlation values between TFR and divorce across lags\"\n)\n```\n:::\n\n------------------------------------------------------------------------\n\n## 1.4 Combined view of Section 1.2 and 1.3\n\nThis section combines the results from Sections 1.2 and 1.3 into a single comparison view. By placing the peak cross-correlation and lag patterns for marriage and divorce side by side, it becomes easier to compare how the two indicators align with fertility across the same lag window.\n\nThis type of summary view is also useful for the planned Shiny application, where users may want to compare multiple indicators interactively in one panel.\n\n::: panel-tabset\n## Visual\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Peak cross-correlation and corresponding lag by indicator\n\n|Pair            | Peak Lag (Years)| Peak Correlation|\n|:---------------|----------------:|----------------:|\n|TFR vs Marriage |                0|            0.878|\n|TFR vs Divorce  |                0|           -0.771|\n\n\n:::\n\n::: {.cell-output-display}\n![](correlation-analysis_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n**Observation:**\\\nThis summary combines the marriage and divorce results into a single comparison view, making it easier to compare their lag structures directly. Both indicators reach their peak cross-correlation with TFR at lag 0, which suggests that the clearest co-movement for both appears in the same year rather than after a longer time shift. However, the direction differs across the two indicators. Marriage shows a positive peak correlation of 0.878, indicating that higher marriage values tend to align with higher fertility, while divorce shows a negative peak correlation of -0.771, indicating that higher divorce values tend to align with lower fertility.\n\nAcross the lag window, the marriage series remains consistently positive and the divorce series remains consistently negative, showing that the two indicators have opposite directional patterns in relation to fertility. This combined chart and table are useful because they provide a concise side-by-side view of both timing patterns and help prepare for the next stage of analysis in the regression section.\n\n## Code\n\n``` r\npeak_ccf_tbl <- bind_rows(\n  get_peak_ccf(ccf_marriage_tbl, \"TFR vs Marriage\"),\n  get_peak_ccf(ccf_divorce_tbl, \"TFR vs Divorce\")\n)\n\nknitr::kable(\n  peak_ccf_tbl,\n  digits = 3,\n  caption = \"Peak cross-correlation and corresponding lag by indicator\"\n)\n\npeak_plot_df <- bind_rows(\n  ccf_marriage_tbl %>% mutate(series = \"TFR vs Marriage\"),\n  ccf_divorce_tbl %>% mutate(series = \"TFR vs Divorce\")\n)\n\nggplot(peak_plot_df, aes(x = lag, y = correlation, colour = series)) +\n  geom_line(linewidth = 1) +\n  geom_point(size = 2) +\n  geom_hline(yintercept = 0, linetype = 2) +\n  labs(\n    title = \"Cross-Correlation Comparison Across Lags\",\n    x = \"Lag (Years)\",\n    y = \"Cross-Correlation\",\n    colour = NULL\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(face = \"bold\"),\n    legend.position = \"top\"\n  )\n```\n:::\n\n------------------------------------------------------------------------\n\n## Conclusion\n\nOverall, the results show that the clearest pattern for both marriage and divorce occurs at lag 0, meaning the strongest alignment with fertility appears in the same year. Marriage displays a positive pattern with fertility, while divorce shows a negative pattern.\n\nThis section therefore provides an exploratory summary of the lag structure in the data and serves as a useful bridge to the panel regression section, where these relationships are examined more formally.\n",
    "supporting": [
      "correlation-analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"site_libs/plotly-binding-4.11.0/plotly.js\"></script>\n<script src=\"site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n<link href=\"site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}