{
  "hash": "7308a74f40382616a9525c351ebba4d3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regression Analysis: Singapore Fertility Trends: A Visual Analytics Study\"\nauthor: \"G1 T16 - Cheok En Qi and Teong Sze Ching\"\ndate: \"March 1, 2026\"\ndate-modified: \"last-modified\"\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n\n## load dataset\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, corrplot, knitr, patchwork)\n\nanalysis_df <- readRDS(\"data/analysis_df.rds\")\ntfr_df <- readRDS(\"data/tfr_df.rds\")\nasfr_df <- readRDS(\"data/asfr_df.rds\")\nseries_key <- readRDS(\"data/series_key.rds\")\n```\n:::\n\n\n\n# Regression Analysis \n\nThis section presents on regression-based analysis to examine whether marriage and divorce indicators can statistically explain fertility trends.\n\nThe regression component is designed to support the planned Shiny application, where users will be able to interactively vary the lag structure of the predictors. As such, the analysis focuses on a baseline current-year model and lagged models that can later be integrated directly into the interactive dashboard. Because these variables change together over time, the regression results should be interpreted as statistical relationships or associations rather than proof of cause and effect.\n\n:::: callout-note\n## 1.1 Baseline Regression Models — Marriage vs Divorce vs Both {.tabset}\n\nThese baseline models examine whether fertility is associated with marriage and divorce in the current period. For example, does fertility in year t move with marriage and divorce in year t?\n\nM1 tests whether marriage alone explains fertility, M2 tests whether divorce alone explains fertility, and M3 examines what happens when both marriage and divorce are included together. Because marriage and divorce data are only available up to 2024, the regressions are estimated using the overlapping non-missing years.\n\n::: panel-tabset\n## Visual\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Baseline regression model comparison\n\n|model                        |  n| r_squared| marriage_coef| divorce_coef|marriage_p |divorce_p |\n|:----------------------------|--:|---------:|-------------:|------------:|:----------|:---------|\n|M1: TFR ~ Marriage           | 45|     0.771|         0.177|           NA|<0.001     |NA        |\n|M2: TFR ~ Divorce            | 45|     0.595|            NA|       -0.552|NA         |<0.001    |\n|M3: TFR ~ Marriage + Divorce | 45|     0.771|         0.182|        0.017|<0.001     |0.878     |\n\n\n:::\n\n::: {.cell-output-display}\n![](regression-analysis_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n**Observation:**\\\nThe baseline regression comparison shows that both marriage and divorce are individually associated with fertility when entered separately. The marriage-only model explains more variation in fertility (R2=0.771) than the divorce-only model (R2=0.595). When both variables are included together, the model fit does not improve beyond the marriage-only model (R2=0.771) and divorce is no longer statistically significant (p=0.878). This suggests that the two indicators may be capturing overlapping long-run demographic patterns, with marriage appearing to be the stronger predictor in the combined specification.\n\nThe coefficient signs are also directionally consistent with the visual trends: marriage has a positive association with fertility, while divorce has a negative association when each is modelled separately.\n\nNote: Although the regression uses 45 overlapping annual observations, the EDA charts do not suggest major isolated outlier years. The series mainly exhibit long-run trends with moderate fluctuations, making the sample acceptable for simple exploratory regression models.\n\n## Code\n\n``` r\nm1 <- lm(tfr ~ marriage, data = analysis_df)\nm2 <- lm(tfr ~ divorce,  data = analysis_df)\nm3 <- lm(tfr ~ marriage + divorce, data = analysis_df)\n\nbaseline_tbl <- tibble(\n  model = c(\"M1: TFR ~ Marriage\",\n            \"M2: TFR ~ Divorce\",\n            \"M3: TFR ~ Marriage + Divorce\"),\n  n = c(nobs(m1), nobs(m2), nobs(m3)),\n  r_squared = c(summary(m1)$r.squared,\n                summary(m2)$r.squared,\n                summary(m3)$r.squared),\n  marriage_coef = c(coef(m1)[\"marriage\"], NA, coef(m3)[\"marriage\"]),\n  divorce_coef  = c(NA, coef(m2)[\"divorce\"], coef(m3)[\"divorce\"]),\n  marriage_p = c(coef(summary(m1))[\"marriage\",\"Pr(>|t|)\"],\n                 NA,\n                 coef(summary(m3))[\"marriage\",\"Pr(>|t|)\"]),\n  divorce_p  = c(NA,\n                 coef(summary(m2))[\"divorce\",\"Pr(>|t|)\"],\n                 coef(summary(m3))[\"divorce\",\"Pr(>|t|)\"])\n)\n\nknitr::kable(\n  baseline_tbl,\n  digits = 3,\n  caption = \"Baseline regression model comparison\"\n)\n\nggplot(baseline_tbl, aes(x = model, y = r_squared)) +\n  geom_col() +\n  geom_text(aes(label = round(r_squared, 3)), vjust = -0.3, size = 3) +\n  labs(\n    title = \"R2 Comparison Across Baseline Regression Models\",\n    x = \"Model\",\n    y = \"R2\"\n  ) +\n  ylim(0, max(baseline_tbl$r_squared) + 0.1)\n```\n:::\n::::\n\n:::: callout-note\n## 1.2 Lagged Regression Models — Testing Delayed Effects {.tabset}\n\nThese models test for delayed effects. Instead of examining whether fertility is associated with marriage and divorce in the same year, is current fertility more strongly related to marriage or divorce in earlier years, such as one or two years before. This is useful because marriage and childbirth do not always happen immediately one after another. A couple may marry in one year and only have children one or two years later. The lagged models therefore help to check whether earlier marriage or divorce patterns explain current fertility better than the current-year model.\n\nL1 tests whether fertility this year is associated with the marriage rate from two years earlier, L2 tests whether fertility this year is associated with the divorce rate from one year earlier, and L3 examines what happens when both lagged predictors are included together.\n\n::: panel-tabset\n## Visual\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Lagged regression model comparison\n\n|model                                  |  n| r_squared| marriage_lag_coef| divorce_lag_coef|marriage_lag_p |divorce_lag_p |\n|:--------------------------------------|--:|---------:|-----------------:|----------------:|:--------------|:-------------|\n|L1: TFR ~ Marriage(t-2)                | 44|     0.636|             0.163|               NA|<0.001         |NA            |\n|L2: TFR ~ Divorce(t-1)                 | 44|     0.557|                NA|           -0.561|NA             |<0.001        |\n|L3: TFR ~ Marriage(t-2) + Divorce(t-1) | 44|     0.641|             0.134|           -0.119|0.004          |0.460         |\n\n\n:::\n\n::: {.cell-output-display}\n![](regression-analysis_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](regression-analysis_files/figure-html/unnamed-chunk-3-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](regression-analysis_files/figure-html/unnamed-chunk-3-3.png){width=672}\n:::\n:::\n\n\n**Observation:**\\\nThe lagged regression models examine whether earlier marriage and divorce patterns are associated with current fertility. Among the single-predictor lagged models, lagged marriage explains more variation in fertility (R2 = 0.636) than lagged divorce (R2 = 0.557). When both lagged predictors are included together, the model fit increases only slightly (R2 = 0.641), with lagged marriage remaining statistically significant (p = 0.004) but lagged divorce becoming insignificant (p = 0.460). Compared with the baseline models, the lagged models do not provide a stronger fit, suggesting that delayed effects may exist but are not more informative than the current-year relationship.\n\nThe scatterplots show that the direction of association remains consistent across the selected lag values: marriage retains a positive relationship with fertility, while divorce retains a negative relationship. However, the lagged patterns do not appear substantially stronger than the baseline same-year case, which is consistent with the regression results.\n\nNote: The scatterplots above use the same lag values as the regression models so that the visual comparisons align directly with the tested baseline and delayed-effect specifications.\n\n## Code\n\n``` r\nlag_m <- 2\nlag_d <- 1\n\nanalysis_lag <- analysis_df %>%\n  mutate(\n    marriage_lag = lag(marriage, lag_m),\n    divorce_lag  = lag(divorce, lag_d)\n  ) %>%\n  drop_na(marriage_lag, divorce_lag, tfr)\n\nm_lag_mar <- lm(tfr ~ marriage_lag, data = analysis_lag)\nm_lag_div <- lm(tfr ~ divorce_lag,  data = analysis_lag)\nm_lag_both <- lm(tfr ~ marriage_lag + divorce_lag, data = analysis_lag)\n\nfmt_p <- function(x) {\n  ifelse(\n    is.na(x), NA,\n    ifelse(x < 0.001, \"<0.001\", sprintf(\"%.3f\", x))\n  )\n}\n\nlag_tbl <- tibble(\n  model = c(\"L1: TFR ~ Marriage(t-2)\",\n            \"L2: TFR ~ Divorce(t-1)\",\n            \"L3: TFR ~ Marriage(t-2) + Divorce(t-1)\"),\n  n = c(nobs(m_lag_mar), nobs(m_lag_div), nobs(m_lag_both)),\n  r_squared = c(summary(m_lag_mar)$r.squared,\n                summary(m_lag_div)$r.squared,\n                summary(m_lag_both)$r.squared),\n  marriage_lag_coef = c(coef(m_lag_mar)[\"marriage_lag\"], NA, coef(m_lag_both)[\"marriage_lag\"]),\n  divorce_lag_coef  = c(NA, coef(m_lag_div)[\"divorce_lag\"], coef(m_lag_both)[\"divorce_lag\"]),\n  marriage_lag_p = fmt_p(c(coef(summary(m_lag_mar))[\"marriage_lag\",\"Pr(>|t|)\"],\n                           NA,\n                           coef(summary(m_lag_both))[\"marriage_lag\",\"Pr(>|t|)\"])),\n  divorce_lag_p  = fmt_p(c(NA,\n                           coef(summary(m_lag_div))[\"divorce_lag\",\"Pr(>|t|)\"],\n                           coef(summary(m_lag_both))[\"divorce_lag\",\"Pr(>|t|)\"]))\n)\n\nknitr::kable(\n  lag_tbl,\n  digits = 3,\n  caption = \"Lagged regression model comparison\"\n)\n\nggplot(lag_tbl, aes(x = model, y = r_squared)) +\n  geom_col() +\n  geom_text(aes(label = round(r_squared, 3)), vjust = -0.3, size = 3) +\n  labs(\n    title = \"R2 Comparison Across Lagged Regression Models\",\n    x = \"Model\",\n    y = \"R2\"\n  ) +\n  ylim(0, max(lag_tbl$r_squared) + 0.1)\n```\n:::\n::::",
    "supporting": [
      "regression-analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}